[[redirects]]
  from = "/api/codewars*"
  to = "https://www.codewars.com/api/v1/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/api/fcc*"
  to = "https://api.freecodecamp.org/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}